apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    containers:
        - name: nginx
          image: nginx
          securityContext:
              privileged: false
          resources:
              limits:
                  cpu: "500m"
                  memory: "256Mi"
